.PHONY: clean cleanall all serwer klient

all:
	cd klient; make
	cd serwer; make

clean: 
	cd klient; make clean
	cd serwer; make clean

cleanall:
	cd klient; make cleanall
	cd serwer; make cleanall

serwer:
	cd serwer; make run

klient:
	cd klient; make run